---
- name: Setup servers
  hosts:
    - clust_servers
  roles:
    - hashi
    - consul
    - vault
    - nomad
    - docker
    - cni
  tags:
    - setup
    - setup-servers

- name: Setup workers
  hosts: clust_workers
  roles:
    - hashi
    - consul
    - nomad
    - docker
    - cni
  tags:
    - setup
    - setup-workers

- name: Setup media worker nfs mounts
  hosts: media_workers
  roles:
    # - hashi
    # - consul
    # - nomad
    # - docker
    # - cni
    - media-nfs
  tags:
    - setup
    - setup-media

- name: Setup nuck
  hosts: nuck
  become: true
  roles:
    - hashi
    - consul
    - nomad
    - docker
    - cni
  tags:
    - setup
    - setup-nuck

- name: Setup coder
  hosts: coder_wrk_0
  roles:
    - hashi
    - consul
    - nomad
    - docker
    - cni
  tags:
    - setup
    - setup-coder
